apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: guestbook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-guestbook
      app: guestbook-app
  template:
    metadata:
      name:  frontend-guestbook
      labels:
        name:  frontend-guestbook
        app: guestbook-app
    spec:
      containers:
      - name: frontend-guestbook
        image: kubernetes/guestbook:v2
        ports:
          - containerPort: 80