apiVersion: v1
kind: Service
metadata:
  name: redis-service-guestbook
  labels:
    name: redis-service-guestbook
    app: guestbook-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: guestbook-app